name: LevelWorld
version: 1.1.4
author: Himmelt
main: org.soraworld.lvlworld.LevelWorld
depend: [Violet]
website: https://github.com/Himmelt/LevelWorld
description: LevelWorld Plugin.
permissions:
  lvlworld.admin:
    default: op
  lvlworld.bypass:
    default: false
