name: LevelWorld
version: 1.1.2
author: Himmelt
main: org.soraworld.lvlworld.LevelWorld
depend: [Violet]
website: https://github.com/Himmelt/LevelWorld
description: LevelWorld Plugin.

commands:
  lvlworld:
    description: "LevelWorld - https://github.com/Himmelt/LevelWorld"
    usage: "/lvlworld save|reload|lang|debug|level|default|force..."
    permission: lvlworld.admin
    permission-message: "You have no permission <lvlworld.admin>"
permissions:
  lvlworld.admin:
    default: op
  lvlworld.bypass:
    default: op
